runtime: custom
env: flex
resources:
  cpu: 4
  memory_gb: 24
  disk_size_gb: 32
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
liveness_check:
  path: "/liveness-check"
  check_interval_sec: 30 # Check every 30 seconds
  timeout_sec: 30 # Allow 30 seconds for a response
  failure_threshold: 5
  success_threshold: 2
  initial_delay_sec: 60 # Don't check for first 60 seconds to allow full boot
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"
readiness_check:
  path: "/readiness-check"
  check_interval_sec: 30
  timeout_sec: 30
  failure_threshold: 5
  success_threshold: 2
  initial_delay_sec: 60
  app_start_timeout_sec: 900